INSERT INTO applications (
    job_id,
    first_name,
    last_name,
    email,
    phone,
    national_id,
    gender,
    location,
    skills,
    previous_position,
    previous_workplace,
    years_of_experience,    
    position_description,
    highest_education,
    major,
    education_institution,
    graduation_year,
    supporting_links,
    cover_letter,
    resume_filename,
    status
)
VALUES
(
    1,
    'Victor',
    'Kamau',
    'victor@example.com',
    '0712345678',
    '12345678',
    'Male',
    'Nairobi',
    '["JavaScript", "Node.js", "Express"]',
    'Software Engineer',
    'Tech Solutions Ltd',
    5,
    'Experienced in building scalable backend systems.',
    'Bachelor\'s Degree',
    'Computer Science',
    'University of Nairobi',
    2018,
    '{"portfolio": "https://victor-portfolio.com", "github": "https://github.com/victor-kamau"}',
    'I am interested in the Backend Developer role.',
    'victor-kamau.pdf',
    'Pending'
),
(
    1,
    'Jane',
    'Mwangi',
    'jane@example.com',
    '0723456789',
    '87654321',
    'Female',
    'Nairobi',
    '["Python", "Django", "REST APIs"]',
    'Backend Developer',
    'Innovatech Ltd',
    3,
    'Specialized in developing RESTful APIs and microservices.',
    'Master\'s Degree',
    'Software Engineering',
    'Kenyatta University',
    2020,
    '{"portfolio": "https://jane-portfolio.com", "github": "https://github.com/jane-mwangi"}',
    'I have three years of backend experience.',
    'jane-mwangi.pdf',
    'Reviewed'
),
(
    2,
    'John',
    'Otieno',
    'john@example.com',
    '0734567890',
    '11223344',
    'Male',
    'Nairobi',
    '["React", "Redux", "TypeScript"]',
    'Backend Developer',
    'Innovatech Ltd',
    5,
    'I am a React developer with five years of experience.',
    'Master\'s Degree',
    'Software Engineering',
    'Kenyatta University',
    2020,
    '{"portfolio": "https://john-portfolio.com", "github": "https://github.com/john-otieno"}',
    'I am a React developer with five years of experience.',
    'john-otieno.pdf',
    'Shortlisted'
);