INSERT INTO jobs (
    title,
    department,
    location,
    employment_type,
    description,
    requirements,
    responsibilities,
    salary,
    currency,
    image_path,
    deadline,
    status
)
VALUES
(
    'Backend Developer',
    'Engineering',
    'Nairobi',
    'Full-time',
    'Develop REST APIs using Node.js and Express.',
    'Node.js, Express, MySQL',
    'Design and implement RESTful APIs, collaborate with frontend developers, and optimize database queries.',
    120000,
    'KES',
    'backend_developer.jpg',
    '2026-12-31',
    'Open'
),
(
    'Frontend Developer',
    'Engineering',
    'Remote',
    'Full-time',
    'Build modern React applications.',
    'React, JavaScript, CSS',
    'Design and implement modern React applications, collaborate with backend developers, and ensure responsive design.',
    110000,
    'KES',
    'frontend_developer.jpg',
    '2026-11-30',
    'Open'
),
(
    'UI/UX Designer',
    'Design',
    'Nairobi',
    'Contract',
    'Design intuitive user experiences.',
    'Figma, Adobe XD',
    'Design and implement intuitive user experiences, collaborate with developers, and ensure usability.',
    90000,
    'KES',
    'ui_ux_designer.jpg',
    '2026-10-15',
    'Open'
),
(
    'HR Officer',
    'Human Resources',
    'Mombasa',
    'Full-time',
    'Manage recruitment processes.',
    'HR experience',
    'Manage recruitment processes, conduct interviews, and ensure compliance with labor laws.',
    80000,
    'KES',
    'hr_officer.jpg',
    '2026-09-30',
    'Draft'
),
(
    'DevOps Engineer',
    'Engineering',
    'Remote',
    'Full-time',
    'Maintain CI/CD pipelines.',
    'Docker, Linux, Kubernetes',
    'Design and implement CI/CD pipelines, collaborate with developers, and ensure smooth deployment processes.',
    150000,
    'KES',
    'devops_engineer.jpg',
    '2026-12-20',
    'Open'
);